craftcms/feed-me

feedme/FeedMe/ElementTypes/Commerce_ProductFeedMeElementType.php, feedme/services/FeedMe_ProcessService.php
Question mark was used instead of colon.
=> Fixed ternary operator

feedme/FeedMe/ElementTypes/EntryFeedMeElementType.php, feedme/FeedMe/Helpers/FeedMeDuplicate.php, feedme/services/FeedMe_ProcessService.php, feedme/templates/feeds/_edit.html
There is a case where we don't want to delete Elements that are not in the feed, but just disable them.
=> Unpublish elements instead of deleting

feedme/services/FeedMe_ProcessService.php
Disabled has been spelt with a double 'e' twice.
=> Fix a typo in Services/FeedMe_ProcessService.php

feedme/controllers/FeedMe_FeedsController.php
In my setup I’m calling `FeedMe_FeedsController::actionRunFeed()` from command line like so:
```
curl --silent --compressed --output /dev/null -H "X-Requested-With: XMLHttpRequest" "http://example.com/index.php/actions/feedMe/feeds/runTask?direct=1&feedId=###&passkey=###”; 
```
As this is not CRON the command waits for the request to end before it can stop, which is not ideal. This PR uses the same code that `TasksController::actionRunPendingTasks()` does to end the request properly so the command can move on.
=> Fixed an issue when triggering feeds from cli.

src/base/Element.php
=> Check against entries that may be currently disabled

feedme/FeedMe/Helpers/FeedMeHelper.php
This adds additional boolean helpers for the values `y` and `n`.
=> Add additional boolean helpers for y/n values

src/elements/Entry.php
Fix for updating parentIds across multiple siteIds
More info in issue: https://github.com/verbb/feed-me/issues/489
-I did minimal testing but it fixes my use case (import entries in a structure from console for siteId > 1 with parents)
=> Entry siteId added

src/base/Element.php
Fix generated slugs for issue #508. I tested it with multiple titles to have the exact same generated slug as Craft.
=> Fix generated slugs for issue #508

src/helpers/BaseHelper.php
I originally added these for the Craft 2 version. I've ported them over to the Craft 3 version.
=> Port additional boolean-like values from Craft 2 version

src/templates/_includes/fields/categories.html, src/templates/_includes/fields/element.html, src/templates/_includes/fields/entries.html, src/templates/_includes/fields/users.html, src/web/twig/variables/FeedMeVariable.php
Fixes https://github.com/craftcms/feed-me/issues/511
=> Fix element fields not having all available custom fields available to match on

docs/feature-tour/feed-overview.md
Changed the wording so it actually makes sense. ;)
=> Fixed wording

CHANGELOG.md, src/fields/Entries.php
Make sure Feed Me finds disabled entries
=> Fixes #645

src/fields/Dropdown.php, src/web/twig/variables/FeedMeVariable.php
Fixes https://github.com/craftcms/feed-me/issues/589
=> Fix optgroup support for Dropdown fields

docs/guides/importing-assets.md
I don't know who Mr. Title is, but this does not belong to him.
=> Fix grammar

CHANGELOG.md, docs/content-mapping/field-types.md, src/fields/GoogleMaps.php, src/services/Fields.php, src/templates/_includes/fields/google-maps.html
This PR will make Feed Me fully compatible with the new **Google Maps** plugin.
Had to sit on this fork while the plugin was still in beta, hope you don't have any merge conflicts. 🤞 
Let me know if you have any questions or hit any snags. Thanks!
=> Added support for Google Maps plugin

src/base/Element.php, src/elements/CalenderEvent.php, src/elements/Category.php, src/elements/Comment.php, src/elements/CommerceProduct.php, src/elements/Entry.php, src/fields/Categories.php, src/fields/Entries.php, src/fields/Tags.php, src/fields/Users.php, src/helpers/AssetHelper.php
Continuation of [this commit](https://github.com/craftcms/feed-me/commit/9030fed0246ba4bd244c5fadc271d869c9714ecc)
=> Fix #649 - Part 2

CHANGELOG.md, src/fields/MultiSelect.php
As done for mapping template - https://github.com/craftcms/feed-me/blob/develop/src/web/twig/variables/FeedMeVariable.php#L63-L86
=> Fix Multi-select/Optgroup import bug

src/services/DataTypes.php
=> Add feedId to EVENT_AFTER_PARSE_FEED

src/elements/User.php
Properly handles active statuses
Fixes #1182
=> Properly set active status

src/fields/Linkit.php
Updates LinkIt field for the new era.
Fixes #1203
=> `fruitstudios` -> `presseddigital`

src/templates/feeds/index.html
Fixes https://github.com/craftcms/feed-me/issues/1189
=> Fix NULL CP trigger causing malformed direct feed urls

docs/developers/events.md
Adds field parsing events to the docs
#669
=> Add field events

src/fields/Assets.php, src/fields/CalendarEvents.php, src/fields/Categories.php, src/fields/CommerceProducts.php, src/fields/CommerceVariants.php, src/fields/DigitalProducts.php, src/fields/Entries.php, src/fields/Tags.php, src/fields/Users.php, src/helpers/DataHelper.php
PHP Stan amends for PR https://github.com/craftcms/feed-me/pull/1229.
It can be merged into v4 and v5.
=> php stan amends

CHANGELOG.md, src/elements/CommerceProduct.php
=> Fixed a bug where importing data to the commerce variant table field don’t work.

src/fields/Matrix.php
Set empty values adjustment for Matrix field in v5.
=> check for importing empty block

src/web/twig/variables/FeedMeVariable.php
Adds support for CKeditor for inner element fields.
Applies to v4 and v5.
=> support ckeditor for inner element fields

src/elements/User.php
Respect the empty photo URL in the feed.
#582
=> respect empty user photo url

CHANGELOG.md
Fixes the 5.1.1.1 release date (2023-02-24 → 2023-03-24).
=> Fix 5.1.1.1 release date

src/helpers/DataHelper.php
Adjusted fetch simple value to only use the default value if it's not empty.
=> fetch simple value update when the default should be used

CHANGELOG.md, src/elements/Category.php
Fixed a bug where Category children of disabled parents will become orphaned. ([#555](https://github.com/craftcms/feed-me/issues/555))
Fixed in this commit f1b9ab0accb0bcaa2e229235e753c13559f0cbcc
=> Bug fix category child import for v4

src/base/DataType.php
Resolve aliases in pagination URL.
#1244
=> resolve aliases in pagination URL

src/fields/Users.php
This PR changes how `Users` field sources are parsed. If not all sources are selected: iterate through the ones that start with `group:` and search for matching users based on the group IDs. The other source that could be selected in Craft 3 is `admins` - if it’s selected, we have to search for the matching user among admins too.
~~This PR should only be merged into `v4`, please.
(I’ll raise a separate one for v5 as there we also have to take care of `credentialed` and `inactive` sources.)~~
It should be ok to merge into v4 and v5, but v5 needs one more PR (#1338) to take care of `credentialed` and `inactive` sources.
#844
=> search through admins if selected as a field source

src/elements/Entry.php
This was partially fixed in https://github.com/craftcms/feed-me/pull/1250
However, there was one leftover spot that was preventing importing entries and creating and assigning a parent in the same import.
=> Fix issue importing parent entries

src/fields/SuperTable.php
This fixes #1364 in the same way #1070 did.
=> Preventing array_merge_recursive with null value with super table, resolving #1364

src/helpers/DataHelper.php
For arrays - checking if the new array already existing and matches values in existing array.
Side conversation with @lindseydiloreto
=> Added check for simple arrays for newValues within existingValues
