README.md
feedme/templates/feeds/_edit.html

Update "duplication handling" terminology within UI and docs to reflect it's full purpose of "import strategy"
I found this very confusing, even after reading the docs. It's not semantically correct in places, but still hard to name.. some suggestions here.

Update confusing "duplication" terminology to "import strategy"

---

feedme/services/FeedMeService.php
feedme/services/FeedMe_FieldsService.php

This PR accomplishes two things...
1. The `postForFeedMeFieldType` hook is called slightly later. This ensures that a valid EntryModel has been established before the hook gets called.
2. The EntryModel is now passed into the hook as a second parameter. This allows the hook to read existing data from the Entry.

Moved `postForFieldType` call, added $entry param

---

feedme/services/FeedMe_FeedService.php

- This is to prevent a 403 error in case the webserver hosting the xml checks whether a useragent is set and denies requests where the useragent is empty or a known spam bot.

Set a user agent on the curl request

---

feedme/services/FeedMe_DataService.php
feedme/services/FeedMe_ProcessService.php

I have a JSON feed with a few nodes that end with a digit. Regex was stripping them out.
`
"images": [
{
"cellLandscape_x3": {
"url": "be4dbdbe267c83abfd2072170f671020_cellLandscape_x3.jpg"
},
"cellLandscape_x2": {
"url": "be4dbdbe267c83abfd2072170f671020_cellLandscape_x2.jpg"
}
}
]
`

Fix regex to handle node names that end in digit

---

feedme/FeedMe/Helpers/FeedMeDateHelper.php

Date Helper currently ignores the incoming date's timezone/offset, as I observed specifically with RSS feeds: both the pubDate (which is RFC 2822, e.g. `Thu, 29 Jun 2017 17:53:12 +0000`) and dc:date (which is ISO 8601, e.g. 2017-06-29T17:53:12+00:00). In stepping through the `parseString` function, I observed that the original timezone was merely stripped and the system timezone applied rather than the datetime being adjusted to the system timezone. This change produces the intended effect, in accordance with Craft's [DateTime::createFromString()](https://craftcms.com/classreference/etc/dates/DateTime#createFromString-detail).

Fix bug that causes datetimes not to be adjusted for timezones on import.

---

feedme/services/FeedMe_ProcessService.php

If multiple FeedMeTask tasks are queued up at the same time, it looks like the same FeedMe_ProcessService gets reused. The problem is that the service isn't particularly re-entrant. Specifically, the properties `_processedElements` and `_processedElementIds` never get reset. It leads to behavior like this:
```
2017/08/22 04:02:14 [info] [plugin] [Forced] Products: Processing 500 elements finished in 169.70s
2017/08/22 04:05:00 [info] [plugin] [Forced] Products: Processing 1000 elements finished in 165.85s
2017/08/22 04:07:57 [info] [plugin] [Forced] Products: Processing 1500 elements finished in 177.21s
2017/08/22 04:11:18 [info] [plugin] [Forced] Products: Processing 2000 elements finished in 200.95s
2017/08/22 04:14:18 [info] [plugin] [Forced] Products: Processing 2500 elements finished …
```

Reset properties to allow an instance of the ProcessService to be reused

---

feedme/FeedMe/Helpers/FeedMeHelper.php

@engram-design In a feed we have a field being mapped to entry status, but it has the values of Active/Inactive. Currently this isn't matched by FeedMe, so I've added it to the boolean helpers list. It is bespoke to this feed, but it seems quite a logical value to have on a general basis? Would you considering have this included upstream?

Add active/inactive values as parseBoolean helpers

---

src/fields/Users.php

If I'm not mistaken, the object instantiated when trying to create a new User from a feed should be of type UserElement not TagElement.

Fix incorrect instantiation of TagElement when creating new Users from a feed

---

feedme/templates/_includes/fields/entries.html

@engram-design Just floating this as an idea. I've come across an issue where I cannot map an item in a feed using the entry default `id`, `title`, `slug` options, because the data cannot match any of those fields, as I'm not in control of the data schema. 
I have had to shamefully modify the `_includes/fields` templates to provide the custom field I need to use for this specific feed item for it to work. This got my thinking it would be nice for entry mapping to be able to also use all the custom fields within the Craft site, rather than just the default three provided.
After a bit of debugging, I was able to split the options array into `defaultFieldOptions` and `customFieldOptions` and then merge them together on the `forms.selectField`. I have limited the `customFieldOptions` array to …

Allow custom entry fields to be used in entry mapping (Craft 2)

---

src/FeedMe.php

Fixes a bug where the plugin may cause Twig to be loaded before it should be, and another bug where the extension might not be available if the Template Mode ever changes from CP to Site, or vise-versa.

Use registerTwigExtension()

---

src/datatypes/Csv.php

We needed an option to set the csv column delimiter to a different character, so i added a config option. Maybe this is useful for others as well?
Would be probably event more useful to be able to configure it on a per Import basis.
`csvColumnDelimiter` defaults to `,`

added config option for csv delimiter

---

feedme/FeedMe/FieldTypes/EntriesFeedMeFieldType.php

This could do with more testing but it fixed an issue for me where Feed Me wasn’t finding existing entries that weren’t in the default locale.
I had it set up to use the slug when finding, the field was set to use a secondary locale and the section containing the entires to be found was disabled in the primary locale and enabled in the secondary one.

Use target locale when finding existing entries.

---

feedme/controllers/FeedMe_LogsController.php

Fixed 404 that would be thrown when clearing logs due to it not prepending the cp trigger e.g. admin.

Fixed 404 error when clearing logs.

---

feedme/variables/FeedMeVariable.php

On initial install, $enabledTabs is not an array and would throw an error. This prevented that error and allowed me to finish set up.

Check that $enabledTabs is array before iteration

---

feedme/FeedMe/Helpers/FeedMeDateHelper.php

As reported originally through support, I think I have found where the +1 hour issue is occurring when importing to the postDate field.
I debugged the date value through the conditions in the DateHelper and found it was correct, right up until `DateTime::createFromString` was used on the dateTimeString and then the time came out as +1.
https://github.com/verbb/feed-me/blob/craft-2/feedme/FeedMe/Helpers/FeedMeDateHelper.php#L71
I then noticed that the second parameter is null. Because the `timezone_type` of my date values is `3` the timezone isn't specified anywhere and because its `null`, Craft defaults to UTC, which isn't ideal because my Craft install itself is using `Europe/London'. So we now have the possibility of a time discrepancy. 
I don't know if this will have any side effects …

Use Craft timezone on parsedDate variable

---

feedme/templates/feeds/_edit.html

When this help text mentions a "primary element", a user might assume it is referring to a container object or root node (as I did). Pluralizing to "primary elements" could prevent this ambiguity.

Clarify primary elements

---

feedme/FeedMe/ElementTypes/EntryFeedMeElementType.php
feedme/FeedMe/Helpers/FeedMeDateHelper.php

This relates to #380 and #388. This forces the built in Craft `postDate` and `expiryDate` date fields to go through the FeedMe Date Helper with `craft()->timezone` used on the output, while leaving other date fields under the original fix made by @kevinsmith in #236.
This seems like a hack, but for whatever reason I am getting inconsistent postDate values imported into Craft with times being +1 on only some imported items, setting the timezone seems to fix the ambiguity, even though most of my imported records are fine without it.
However I have discovered that using `craft()->timezone` across all of the date fields causes issues with those date/time fields, so this only is done on the Craft `postDate` and `expiryDate` fields. It requires a third optional parameter to the FeedMeDateHelper …

Use Craft timezone on postDate/expiryDate fields

---

src/FeedMe.php

This change will prevent an error if you install the feed-me plugin from CLI (`./craft install/plugin feed-me` or via a plugin like schematic).
Before change:
```
./craft install/plugin feed-me             
*** installing feed-me
> create table {{%feedme_feeds}} ... done (time: 0.017s)
*** failed to install feed-me: Calling unknown method: craft\console\controllers\InstallController::redirect()
```
After change:
```
./craft install/plugin feed-me
*** installing feed-me
> create table {{%feedme_feeds}} ... done (time: 0.014s)
*** installed feed-me successfully (time: 0.034s)
```

Prevent redirect call if plugin is installed from CLI

---

src/elements/CalenderEvent.php
src/templates/_includes/elements/calendar-event/map.html

This allows Solspace Calendar's "SELECT_DATES" data to be imported.
A couple of notes on this:
1. Required the "Repeat Frequency" to be set to "SELECT_DATES"
2. The import assumes an array for the "SELECT_DATES" data
3. Date format for each "SELECT_DATES" date needs to be: YYYY-MM-DD
To dos:
1. It should probably check that "Repeat Frequency" is "SELECT_DATES" before processing this data.
2. Please check the "_onAfterElementSave" function is using the best method for finding the corresponding event element.
3. Could allow the user to specify the date format of "SELECT_DATES" dates.

Allows SELECT_DATES to be imported.

---

composer.json
composer.lock

The Carbon maintainers released a new version of Carbon recently and I'm having issues using the latest features in our Craft site because the feed-me plugin is limited to carbon v1. Carbon v2 has some breaking changes, but feed-me does not appear to rely on any of those changed features.

Upgrades to nesbot/carbon ^2.10

---

src/base/Element.php

Fixes namespace issue for `use craft\feedme\events\ElementEvent;`
Fixes https://github.com/craftcms/feed-me/issues/563 and https://github.com/craftcms/feed-me/issues/565

Fix missing namespace

---

CHANGELOG.md
src/elements/Entry.php
src/helpers/DataHelper.php

Default values were being passed as strings which would break [here](https://github.com/craftcms/feed-me/blob/develop/src/fields/Checkboxes.php#L40) and [here](https://github.com/craftcms/feed-me/blob/develop/src/fields/MultiSelect.php#L40)

Fix importing default value for checkboxes and multiselects

---

src/services/Feeds.php

Fixes #643 
New in 3.4: https://github.com/craftcms/cms/blob/3.4/CHANGELOG-v3.4.md#changed
> Active record classes now normalize attribute values right when they are set.
Since feed-me was trying to decode the `Record` props directly, they were getting encoded again.
@brandonkelly Seems like this could potentially trip up other plugins that might be modifying a Record instance directly…maybe worth a warning in the changelog?

Fix _createModelFromRecord for Craft 3.4

---

src/queue/jobs/FeedImport.php
src/services/Process.php

The proposed changes adds the feed data returned from `EVENT_BEFORE_PROCESS_FEED` to the return array, and counts the number of items _after_ `beforeProcessFeed()` is called, instead of before. This gives the ability to actually modify the feed data via the `EVENT_BEFORE_PROCESS_FEED` event.
The change in #462 give the `EVENT_BEFORE_PROCESS_FEED` the ability to change the $feedData in the event. However, as nothing else is happening in the `beforeProcessFeed()` function, and the feed data is not part of the `$return` array returned from the function, any changes made to the actual feed data is effectively lost.
Furthermore, as the items in the feed data are counted _before_ `beforeProcessFeed()` is called, any changes to the number of items in the feed (e.g. removing duplicates), will …

Returning feedData from beforeProcessFeed() and counting the number of items after, instead of before

---

src/services/DataTypes.php

`UrlHelper::isRootRelativeUrl($url)` should be `true` and  already checks `!UrlHelper::isProtocolRelativeUrl($url)` (previously changed [here](https://github.com/craftcms/feed-me/issues/624))

Fix issue #647

---

CHANGELOG.md
src/templates/_includes/fields/_base.html
src/templates/_includes/fields/entries.html

This helps making sure disabled entries are displayed in modals (related to #645 and [#5682](https://github.com/craftcms/cms/issues/5682))

Adds the ability to set criterion on elementselect fields

---

src/elements/Asset.php

it seems when feed-me create an asset,  it always find element for primary site id. so if target site Id is not primary site, it add/updates element for wrong site.
this PR add siteId of target site to criteria to find correct element record after asset creation.
**Related issues**
for example https://github.com/craftcms/feed-me/issues/658 has same scenario.

Fix siteId not applied to asset find query

---

docs/get-started/configuration.md

Setting "logging" to "errors" does nothing the right value seems to be "error"

Fix documentation of the for error log level

---

src/helpers/DataHelper.php

A feed is unable to set an Entry's status to disabled. The issue comes down to the first value comparison check being against a non-existent value in the `$fields` array. `Hash::get()` will return a default of `null` which when compared with a double-equals comparison results in `true` and causes the difference to be thrown away. The second comparison against the `$attributes` array has the desired result since it does exist in that array. I placed the same check on Line 197 for the same purpose as on Line 178.
Further details of the issue can be found in the initial report on #760.

Issue 760: Entry status not changing to disabled

---

docs/guides/migrating-from-expressionengine.md

"Its" was used instead of "it's," and perhaps a contraction is not suitable for documentation anyway. "Essentially" was, well, inessential.

Grammar fix in migrating-from-expressionengine.md

---

CHANGELOG.md
src/elements/CalenderEvent.php

CalendarEvent import breaks if an *RRULE* contains rules which aren't used by Calendar.
This happens because all RRULEs are being set as properties to the element even when no such properties exist.
The provided fix defines a list of all allowed RRULE properties and provides their property names, thus if the RRULE contains anything extra, it's not attached to the element attribute value list.

Fix: CalendarEvent breaking on extra RRULE entries

---

src/templates/feeds/_map.html

When importing a large number of fields, the "map to feed item" dropdown on the map page is very cumbersome. Sorting the list alphabetically makes it much easier to navigate.

Sort feed data dropdown alphabetically

---

src/console/controllers/FeedsController.php

Add the ability to push all feeds to the queue.
Existing functionality remains the same.
Pushing all feeds to the queue will ignore supplied id's, limit and offset. The continueOnError flag can still be passed down.
Building a multi-site Craft app with ever expanding sites and feed-me imports which have to be manually specified for every new feed makes it easy to forget updating the cron config. Allowing the --all tag for the command removes that.

Run all feeds

---

docs/troubleshooting.md

Debug toolbar will crash platform on any sizeable feed-me import as it's constant calls to Yii's getRawSql causes memory leaks that eventually consume all available memory on the host machine.

Include warning about debug toolbar in troubleshooting.md

---

src/base/Element.php

`mb_strtolower` in `Element::parseSlug` breaks `allowUppercaseInSlug` configuration
Was lowercased before running the feed.
#865

Fixes #865: Removed `mb_strtolower` in Element::parseSlug to handle allowUppercaseInSlug

---

src/services/Process.php

Hey there!
I've managed to figure out how to handle nested importing for child elements, starting with the Comments plugin. The bulk of the work is done in the Comments plugin https://github.com/verbb/comments/commit/b4a52860097569b6239c18b71d53a1956c160861 but there's a tiny change that needs to be made on Feed Me's end. This is to facilitate custom data when calling `processFeed()` on-demand.
By default, Feed Me doesn't expect the feed data to change, so it'll prep it in `beforeProcessFeed()` and then `processFeed()` steps through each item. Not sure who thought that was a good design decision 🙄
But with these two changes, you can import nested data in one shot, with a feed structures as:
```
[
{
"owner": "Feed Me Owner",
"comment": "1-1 level comment",
"children": [
{
"owner": "Feed Me …
```

Allow `processFeed()` to accept a `feedData` attribute as an override

---

CHANGELOG.md
src/templates/feeds/_edit.html

Fix [an issue](https://github.com/craftcms/feed-me/issues/1065) that could happen when creating or editing a feed since Craft 3.7.24 ([this change](https://github.com/craftcms/cms/commit/8ec647c47fcdcc61cb021c3b60c2393a9ef949b8))

This is not a field

---

src/elements/Entry.php

Craft 4 has ditched the `newParentId` property, so we need to use `setParentId()`. For some reason, `$element->parentId = 123` doesn't seem to work, despite the setter there, as I've found for https://github.com/verbb/comments/commit/83f83adea83274630379d479413ae30c03566b35 and https://github.com/verbb/navigation/commit/7a0b4bcd6e9ce82dcefd200ab515eefe29f8b6f4

Replace `newParentId` with `setParentId()`

---

src/base/Element.php
src/elements/Entry.php
src/fields/Entries.php

This addresses a few issues we ran into while testing out feed processing in `5.0.0-beta.2` on a site running Craft `4.0.0-RC1`.
**Date Processing**
With the `?DateTime` return type added to `Element::parseDateAttribute()`, feeds setting a date (like a `postDate` or `expiryDate`) would throw some variation of:
```
craft\\feedme\\base\\Element::parseDateAttribute(): Return value must be of type ?DateTime, string returned - Element.php: 331
```
This flattens any returned `Carbon` instances down to a raw `DateTime`, and ensures empty strings and arrays are returned as `null`.
**Parent Attachment**
Feeds attaching an element to a parent would throw
```
Setting unknown property: craft\\elements\\Entry::newParentId - Component.php: 209
```
This swaps the old `newParentId` property for …

Fix Craft 4 feed processing errors

---

src/datatypes/Csv.php

League CSV 9's ResultSet is an object and casting it to an array causes chaotic behavior. Just keep it as mixed.
CSV reader in 5.0 has been consistently malfunctioning in unpredictable ways, e.g. reporting different element count or reporting errors that are not at all helpful.

Csv: Fix unintended cast

---

src/services/DataTypes.php

(cherry picked from commit b472eaba2892cd7727fa9b62c85dbcac4df3f967)
Backports #1139 to v4.
#1107

Add feedId to EVENT_AFTER_PARSE_FEED

---

src/services/Process.php

The `enabledForSite` property was getting set correctly, but the `enabled` property didn't necessarily respect it. This caused elements to appear as if their status was incorrect and could cause some issues if you tried to change it via an element action.
Fixes #1208

Fix enabled logic

---

src/web/twig/variables/FeedMeVariable.php

The `null` check was flipped, which meant that subfields wouldn't show when they existed.

Properly show sub fields

---

CHANGELOG.md
src/helpers/DataHelper.php

Same fix as #1218, just onto the v4 branch instead.
@boudewijn-zicht deserves all the credit.
It looks like this was originally `$attributes` but accidentally got swapped to `$fields` in the [`__compareSimpleValues` refactor](https://github.com/craftcms/feed-me/commit/704d511e85adba8caca7a90644c29e78b0a3490a)
Fixes #1219

Compare $attributes not $fields

---

src/helpers/DataHelper.php

When you would import any of an elements attributes, say its title, then this would always conclude that the value changed because it was comparing its hash in the wrong array
`$value` contains the values of custom fields, `$attributes` contains the values of element attributes such as its title.
This bug causes all imports, that import any of the attributes, to always conclude that the data changed.  This results in more database work and also a new revision for every entry on every import.
Resolves #1219

Fixes compareElementContent

---

src/templates/_includes/fields/_base.html
src/templates/_includes/fields/calendar-events.html
src/templates/_includes/fields/categories.html
src/templates/_includes/fields/commerce_products.html
src/templates/_includes/fields/commerce_variants.html
src/templates/_includes/fields/digital-products.html
src/templates/_includes/fields/entries.html
src/templates/_includes/fields/tags.html
src/templates/_includes/fields/users.html

At the moment, when mapping relational fields for import, the default value modal shows all available sources and not just the sources allowed for the field.
This PR limits the default value option to the sources specified for the field. It’s applied to all relational fields supported by Feed Me, except for the assets field (as per our chat on 23/01/2023).
I’m worried that this could be considered a breaking change, though. Happy to discuss this further, and maybe it should be postponed until the Craft 5 release.
It can be applied to v4 and v5.

limit relational field default value options to field's sources

---

src/helpers/DataHelper.php

When the values are empty arrays we do NOT use Hash::check because that will always return false, hence even when both values are empty arrays the result will still be that the values are different and have to be imported
Fixes #1238

Fix comparing empty arrays

---

src/fields/GoogleMaps.php
src/templates/_includes/fields/google-maps-before-4-3.html

Patches a compatibility issue with the Google Maps plugin (if using GM v4.3+).
> NOTE: If patching an existing feed, it may be necessary to **remap the Address subfields**.
https://github.com/doublesecretagency/craft-googlemaps/issues/78

Fixed compatibility with Google Maps plugin v4.3+

---

src/base/Element.php

If an element is already disabled (globally or for the site), don’t disable it again and don't trigger an unnecessary resave.
A copy of: https://github.com/craftcms/feed-me/pull/736 + additional safeguard for `disableForSite()`.
#1241

don't disable already disabled elements

---

src/helpers/DataHelper.php

Allowing empty values works great, except it was freaking out for Checkbox and Multi Select fields which expect an array value, not a string. Added new safeguard to change an empty string to an empty array before `in_array` checks for those fields.
PR #1228

make sure empty value is changed to an array

---

src/web/assets/feedme/FeedMeAsset.php

Fixed a type-o after webpack conversion. Applies to both v4 and v5 of the plugin.
#1257 
#1258 
#1259

fixed type-o after webpack conversion

---

src/helpers/DataHelper.php

Make the new `$feed` param in `DataHelper::fetchValue()` optional.
#1264

make $feed param in DataHelper::fetchValue optional

---

src/helpers/DataHelper.php

Using default value shouldn’t be linked to `setEmptyValues`.
For v4 and v5.

using default value shouldn't be linked to setEmptyValues

---

src/web/twig/variables/FeedMeVariable.php

Correct namespace for the Redactor field used for importing inner element fields.
This can be merged into v5 too or Oli’s PR can be used: https://github.com/craftcms/feed-me/pull/1274

correct namespace for redactor field as subfield

---

src/base/Field.php
src/fields/Assets.php
src/fields/Categories.php
src/fields/Entries.php
src/fields/Matrix.php
src/fields/Tags.php
src/fields/Users.php

This PR fixes en issue where: if you have a matrix field with e.g. entries field in it and for that entries field you want to map inner element fields, content from the first entry is used to populate all other entries.
#1227

fix for matrix element inner fields using first set of data for all entries

---

src/fields/Matrix.php

When importing values to Matrix blocks via “Use default value”, incorrect data was used.
E.g. default assets were not used, a wrong copy was imported, and so on.
This PR changes how “use default” for matrix blocks is processed.
Applies to v4 and v5.
#674

different approach to importing default vals for matrix

---

src/helpers/DataHelper.php

`DataHelper::fetchValue` amends to allow the use of 'usedefault' for mapping values and to only `count()` arrays.
#1304

data helper fetch value amends

---

src/models/Settings.php
src/services/Logs.php

The `Settings` model `$logging` should allow for `bool` and `string`, so the logging level can be set to `'error'` as per the docs.
Only for v5.
#1295

logging level bug fix

---

src/helpers/DataHelper.php

Fixed a bug where having the `$value` set to `null` to start with (needed for `setEmptyValues)` was causing an error with `array_merge` if the field value was delimited.
#1298

fix for array_merge brought on by setEmptyValues works

---

src/templates/_includes/elements/commerce-products/map.html

Adds `type` to the `datetime` fields for the Commerce Products mapping screen. 
It’s only throwing an error in v5 but should be added to v4 and v5 for consistency.
To take effect, you need to re-save your feed, so that the date fields get the formatting option (currently missing from the mapping screen for Commerce Products).
#1287

add formatting dropdown to mapping dated for products

---

src/Plugin.php
src/elements/Entry.php
src/services/Process.php

When importing entries to a section with the custom propagation method, check if the entry exists for other sites supported by this section. If it does, enable it for the site we’re importing to before updating the content.
Only applicable to v5 and requires Craft 4.4.8.
#1279

support for importing entries with custom propagation

---

src/helpers/DataHelper.php

Currently the comparison fails when importing matrixes, this causes imports to incorrectly assume that the data changed and hence resulting in more database work, unncessessary revisions and a less efficient import alltogether.
I'm not sure in what version you would like this fix to be applied.  Give a shout if I have to move it around.
https://github.com/craftcms/feed-me/issues/1291

Adds recursive comparison when dealing with Matrix

---

src/helpers/DataHelper.php
src/services/Process.php

After adding `setEmptyValues` boolean and numeric values (`false`, `0`) were not importing correctly if `setEmptyValues` was turned off.
#1329

respect bool and numeric values

---

src/fields/Money.php
src/templates/_includes/fields/money.html

Adds money field template with “Data provided for this localized for the site the feed is for” checkbox. 
If checked, the value provided in the feed will be parsed as localised for the site you’re importing to. 
If left unchecked, a float-like notation will be used to parse.
Dutch number formatting uses a `full stop` as a **grouping character** and a `comma` as a **decimal character**.
Polish number formatting uses a `space` as a **grouping character** and a `comma` as a **decimal character**.
English number formatting uses a `comma` as a **grouping character** and a `full stop` as a **decimal character**.
You have a Money field with EUR currency.
You want to import a value of **one thousand two hundred thirty-four euro and fifty-six cents** into that field.
**Example 1:**
- the site …

money value in the feed should be float-like

---

src/fields/DefaultField.php

Allow to `setEmptyValues` for `HtmlField` type fields - Redactor, CKEditor.
`HtmlField->serializeValue` changes the empty string to `null`, which causes `setEmptyValues` to not take effect.
#1321

setEmptyValues for html fields (redactor, ckeditor)

---

src/helpers/DataHelper.php
src/services/Process.php

If element status is the only thing that should get updated, and the `compareContent` is set to `true` (default), the status wasn’t being updated because the content comparison check wasn’t taking `enabled` and `enabledForSite` into account.
#1310

check if element enabled(forSite) attribute(s) changed

---

src/services/DataTypes.php

Trigger the `EVENT_AFTER_FETCH_FEED` event if the feed is defined with a local path, too (e.g. `@webroot/feed-me/my-data.json`).
#1101

trigger event_after_fetch_feed if feed path is local

---

src/fields/Users.php

v5 version of [PR 1337](https://github.com/craftcms/feed-me/pull/1337).
It has the same approach to handling groups and admins, and adds handling of `credentialed` and `inactive` sources.
#844

search through admins, credentialed and inactive if selected as a field source

---

src/base/Element.php

This PR adjust the slug-importing behaviour. If the slug from the feed is considered valid (after normalization), it will be used; otherwise, it will do what it does now - run it through the [`_createSlug()` method](https://github.com/craftcms/feed-me/blob/develop/src/base/Element.php#L350-L359), which will turn it into a kebab-cased string. 
Before this change (assuming you haven’t changed the  `slugWordSeparator` config):
- if you have a slug: `test_1` in your feed, it will be imported as `test-1`
- if you have a slug: `tes't_1` in your feed, it will be imported as `test-1`
- if you have a slug: `test-1` in your feed, it will be imported as `test-1`
- if you have a slug: `test 1` in your feed, it will be imported as `test-1`
After:
- if you have a slug: `test_1` in your feed, it will be …

respect importing valid slugs

---

src/base/Element.php
src/web/twig/variables/FeedMeVariable.php

Allow the parent field to be a unique identifier. 
It can be used along with, e.g. the title to allow to import a unique structure like this: 
#780

allow parent to be a unique identifier

---

src/fields/Categories.php
src/fields/CommerceProducts.php
src/fields/CommerceVariants.php
src/fields/DigitalProducts.php
src/fields/Entries.php
src/helpers/DataHelper.php

In the CMS, it is possible to create elements with the title (or slug) set to `"0"` or `"false"`. Feed Me can have trouble finding (and creating) elements with the title (or slug) of `"0"`.
Allow to match and create Category, Entry, Product, and Digital Product with title or slug set to a zero in the feed.
For Product Variant, do the same but just for the title.
#1102

match and create elements with title or slug "zero"

---

src/fields/Matrix.php
src/fields/SuperTable.php
src/services/Fields.php

If Categories or Tags have been entrified, the fields could have been changed to Entries field, but the feed still refers to them by their original type. Because of that, check if the field we got by handle matches the type saved in the feed, and if it doesn’t, use the Entries field type.
Once the feed is saved after entrification, the field type gets updated, so the code that changes the field type won’t be executed anymore.
(Just for Craft 4.) 
#1340

handle entrified categories and tags fields

---

src/helpers/AssetHelper.php
src/queue/jobs/FeedImport.php

Don’t ignore `queueTtr`, `queueMaxRetry` and `assetDownloadCurl` feed options.
#1356

don't ignore feed options

---

src/fields/Assets.php
src/fields/CalendarEvents.php
src/fields/Categories.php
src/fields/CommerceProducts.php
src/fields/CommerceVariants.php
src/fields/DigitalProducts.php
src/fields/Entries.php
src/fields/Users.php

When importing into relational fields, use the new `maxRelations` setting, not the old `limit`.
#1354

use maxRelations, not limit for the relational fields

---

src/services/Process.php

Process `enabled` and `enabledForSite` attributes before bulk-setting the rest of element attributes.
#1208

order of events for setting enabled & enabledForSite

---

src/services/Feeds.php

When overriding feed settings via `config/feed-me.php` account for setting a value to `false`.
#1380

allow to override to `false` value

---

src/base/Field.php

Commit https://github.com/craftcms/feed-me/commit/27dac31b8a6070d8e15d480d5c55f6d2fa20af21 fixed [an issue](https://github.com/craftcms/feed-me/issues/1227) where matrix element inner fields were using the first set of data for all elements, but it broke “simple” inner element field import. This PR fixes it while keeping the inner fields for elements in a matrix field working as expected. 
#1378

fix for importing inner element fields
